version: '3'
services:
  # Serviço para o aplicativo Go
  app:
    build: .
    volumes: 
      - .:go/app
    platform: linux/amd64 
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  # Serviço para o MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: products
    ports:
      - "3307:3306"

  # Serviço para o Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-container
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # Serviço para o ZooKeeper (necessário para o Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181" # Porta para acessar o ZooKeeper
